name: Build

on:
  workflow_dispatch:
    {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Build Directory
        shell: bash
        run: mkdir build

      - name: Build
        working-directory: build
        run: cmake ..

      - name: Compile
        working-directory: build
        run: cmake --build .
