name: Test

on:
  workflow_dispatch:
    {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Build Directory
        shell: bash
        run: mkdir build

      - name: Enable Testing
        shell: bash
        run: cmake -S . -B build -DBUILD_TESTS=ON

      - name: Build
        working-directory: build
        run: cmake ..

      - name: Compile
        working-directory: build
        run: cmake --build .

      - name: Test
        working-directory: build
        run: |
          ctest -C DEBUG --output-junit testResult.xml
          sed -i 's/<testsuite name="(empty)"/<testsuite name="Unit Tests"/' testResult.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: build/*.xml

      - name: Upload Results
        uses: dorny/test-reporter@v2
        with:
            fail-on-empty: "false"
            name: Test Results
            path: "build/*.xml"
            reporter: java-junit
