name: Test

on:
  push:
    branches:
      ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Build Directory
        shell: bash
        run: mkdir build

      - name: Enable Testing
        shell: bash
        run: cmake -S . -B build -DBUILD_TESTS=ON

      - name: Build
        working-directory: build
        run: cmake ..

      - name: Compile
        working-directory: build
        run: cmake --build .

      - name: Test
        working-directory: build
        run: |
          ls -la tests
          ./tests/Debug/test_login --reporter junit --out test_login.xml
          ./tests/Debug/test_forums --reporter junit --out test_forums.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: build/*.xml

      - name: Upload Results
        uses: dorny/test-reporter@v2
        with:
            fail-on-empty: "false"
            name: Test Results
            path: "build/*.xml"
            reporter: java-junit
